/* eslint-disable @typescript-eslint/no-namespace */
/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

import * as _0 from "./Wrapper.types";
import * as _1 from "./Wrapper.client";
export namespace contracts {
  export const Wrapper = { ..._0, ..._1 };
}
