/**
 * This file was automatically generated by @cosmwasm/ts-codegen@0.17.0.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
 * and run the @cosmwasm/ts-codegen generate command to regenerate this file.
 */

export type ExecuteMsg =
  | {
      swap: {
        amount: Uint128;
        first: Swap;
        max_output: Uint128;
        min_output: Uint128;
        route: Step[];
        user: string;
        [k: string]: unknown;
      };
    }
  | {
      check_range: {
        balance_before: Uint128;
        denom: string;
        max_output: Uint128;
        min_output: Uint128;
        user: string;
        [k: string]: unknown;
      };
    };
export type Uint128 = string;
export interface Swap {
  denom_in: string;
  denom_out: string;
  pool_id: number;
  [k: string]: unknown;
}
export interface Step {
  denom_out: string;
  pool_id: number;
  [k: string]: unknown;
}
export interface InstantiateMsg {
  [k: string]: unknown;
}
