[package]
name = "osmo-bindings"
version = "0.6.0"
authors = ["Ethan Frey <ethanfrey@users.noreply.github.com>"]
edition = "2018"
description = "Bindings for CustomMsg and CustomQuery for the Osmosis blockchain"
repository = "https://github.com/confio/osmosis-bindings"
homepage = "https://osmosis.zone"
license = "Apache-2.0"

[dependencies]
cosmwasm-std = { version = "1.1.4", features = ["iterator"] }
schemars = "0.8.11"
serde = { version = "1.0.145", default-features = false, features = ["derive"] }

[dev-dependencies]
cosmwasm-schema = { version = "1.1.4", default-features = false  }
